apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: myapp
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-pvc
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: pvc-1

