apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
  namespace: myapp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi

