apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
spec:
  selector:
    matchLabels:
      app: attendance-service
  replicas: 1
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
        - name: attendance-service
          image: parkjunhyeon/msa_attendance:v1
          imagePullPolicy: Always  # ⭐ 추가된 부분
          ports:
            - containerPort: 6060
          envFrom:
            - secretRef:
                name: attendance-secret
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  selector:
    app: attendance-service
  ports:
    - port: 6060
      targetPort: 6060
  type: ClusterIP
