apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  selector:
    matchLabels:
      app: finance-service
  replicas: 1
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
        - name: finance-service
          image: parkjunhyeon/msa_finance:v1
          imagePullPolicy: Always  # ⭐ 추가된 부분
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: finance-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
