apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-auth
  template:
    metadata:
      labels:
        app: redis-auth
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-auth
  namespace: default
spec:
  selector:
    app: redis-auth
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30680
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-resv
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-resv
  template:
    metadata:
      labels:
        app: redis-resv
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-resv
  namespace: default
spec:
  selector:
    app: redis-resv
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30679
  type: NodePort

