apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: parkjunhyeon/msa_user:v1
          imagePullPolicy: Always  # ⭐ 추가된 부분
          ports:
            - containerPort: 7070
          envFrom:
            - secretRef:
                name: user-secret
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 7070
      targetPort: 7070
  type: ClusterIP
